apiVersion: apps/v1
kind: Deployment
metadata:
  name: game3
  namespace: game3
  labels:
    app: game3
    environment: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game3
  template:
    metadata:
      labels:
        app: game3
        environment: demo
    spec:
      containers:
      - name: game3
        image: dockerghosh/githubsearchfrontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http-web
