apiVersion: v1
kind: Service
metadata:
  labels:
    app: game3
  name: game3
  namespace: game3
spec:
  ports:
    - port: 80
      targetPort: http-web
      protocol: TCP
      name: http
  selector:
    app: game3
