apiVersion: apps/v1
kind: Deployment
metadata:
  name: game2
  namespace: game2
  labels:
    app: game2
    environment: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game2
  template:
    metadata:
      labels:
        app: game2
        environment: demo
    spec:
      containers:
      - name: game2
        image: dockerghosh/githubsearchfrontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http-web
