apiVersion: v1
kind: Service
metadata:
  labels:
    app: game2
  name: game2
  namespace: game2
spec:
  ports:
    - port: 80
      targetPort: http-web
      protocol: TCP
      name: http
  selector:
    app: game2
