apiVersion: apps/v1
kind: Deployment
metadata:
  name: game4
  namespace: game4
  labels:
    app: game4
    environment: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game4
  template:
    metadata:
      labels:
        app: game4
        environment: demo
    spec:
      containers:
      - name: game4
        image: dockerghosh/githubsearchfrontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http-web
