apiVersion: v1
kind: Service
metadata:
  labels:
    app: game4
  name: game4
  namespace: game4
spec:
  ports:
    - port: 80
      targetPort: http-web
      protocol: TCP
      name: http
  selector:
    app: game4
