apiVersion: v1
kind: Service
metadata:
  labels:
    app: game1
  name: game1
  namespace: game1
spec:
  ports:
    - port: 80
      targetPort: http-web
      protocol: TCP
      name: http
  selector:
    app: game1
